# Generated by Django 3.2 on 2021-04-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0006_auto_20210405_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_releases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('about_author', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='uploads/new_releases/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wadapp.category')),
            ],
        ),
    ]
