# Generated by Django 3.1.6 on 2021-04-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_releases',
            name='preview',
            field=models.FileField(default='', upload_to='new_releases_previews/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new_releases',
            name='about_author',
            field=models.CharField(default='', max_length=2000000),
        ),
        migrations.AlterField(
            model_name='new_releases',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000000, null=True),
        ),
        migrations.AlterField(
            model_name='new_releases',
            name='image',
            field=models.ImageField(upload_to='new_releases/'),
        ),
    ]
