# Generated by Django 3.1.6 on 2021-04-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0009_auto_20210413_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_releases',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
    ]
