# Generated by Django 3.1.6 on 2021-04-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0010_new_releases_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dlprice', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='download_books/')),
                ('preview', models.FileField(upload_to='download_books_previews/')),
                ('download', models.FileField(upload_to='download_books_pdf/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wadapp.category')),
            ],
        ),
    ]
