# Generated by Django 3.1.6 on 2021-04-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0011_downloadbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadbook',
            name='category',
        ),
    ]
