# Generated by Django 3.1.6 on 2021-04-14 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0012_remove_downloadbook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadbook',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wadapp.category'),
        ),
    ]
