# Generated by Django 3.1.6 on 2021-04-24 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0013_downloadbook_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='main_books')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wadapp.category')),
            ],
        ),
    ]
