# Generated by Django 3.1.6 on 2021-05-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0016_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_releases',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Usedbook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=1000000, null=True)),
                ('aboutauthor', models.CharField(blank=True, default='', max_length=1000000, null=True)),
                ('image', models.ImageField(upload_to='usedbooks/')),
                ('preview', models.FileField(upload_to='usedbooks_previews/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wadapp.category')),
            ],
        ),
    ]
