# Generated by Django 3.1.6 on 2021-05-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0017_auto_20210501_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dlprice',
        ),
    ]
