# Generated by Django 3.1.6 on 2021-05-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0018_remove_product_dlprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='newbook',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='wadapp.new_releases'),
        ),
        migrations.AddField(
            model_name='order',
            name='usedbook',
            field=models.ForeignKey(default=150, on_delete=django.db.models.deletion.CASCADE, to='wadapp.usedbook'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wadapp.product'),
        ),
    ]
