# Generated by Django 3.1.7 on 2021-05-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0019_auto_20210501_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(default='anonymous', max_length=50)),
                ('bookname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('reviews', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=4)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
