# Generated by Django 3.1.7 on 2021-05-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadapp', '0020_auto_20210506_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='emailid',
            field=models.EmailField(default='Anonymous', max_length=50),
        ),
    ]
